### ISSUE TITLE
Allow custom amplitude instance for use with CommonJS packagers

### ISSUE THREAD

**Issue by marcello3d** [rangle/redux-beacon#136]
Currently in our codebase we have to do the following:
```js
window.amplitude = require('amplitude-js')
module.exports = require('redux-beacon/targets/amplitude')
```

Which we then import and use: 
```js
import amplitude from 'amplitude-js'
import { createMiddleware } from 'redux-beacon'
import { Amplitude } from './redux-beacon-amplitude'

…
amplitude.getInstance().init(…)
createMiddleware(eventsMap, Amplitude, { offlineStorage })
```

It would be nice if redux-beacon-amplitude either required amplitude-js directly (peer dependency?) or could be passed in somehow (e.g. `createMiddleware(eventsMap, amplitudeMiddleware(amplitude), { offlineStorage })`.

**Comment by ttmarek** [comment]
This is a great suggestion @marcello3d!

I think the latter solution (passing it in) would be the simplest most maintainable solution. Something like:

```js
import amplitude from 'amplitude-js';
import { createMiddleware } from 'redux-beacon'
import { Amplitude } from 'redux-beacon/amplitude'

// initialise amplitude
amplitude.getInstance().init(API_KEY)


// create analytics middleware
const options = { instance: amplitude.getInstance('INSTANCE_NAME') };
const middleware = createMiddleware(eventsMap, Amplitude(options), { offlineStorage });
```

If an amplitude instance is provided the target would use that to track events, otherwise it will look for `window.amplitude` and use the default instance (i.e. `window.amplitude.getInstance()`).

Thoughts?

@bertrandk, I'd like to hear your thoughts on this as well.

**Comment by bertrandk** [comment]
Passing it in would definitely be the way to go. I can probably make the change sometime this evening if nobody else gets to it first.

**Comment by ttmarek** [comment]
This is now the default, documented, way to use the Amplitude target!
https://rangle.gitbook.io/redux-beacon/targets/amplitude
