### ISSUE TITLE
Creating events map for React Navigation action types

### ISSUE THREAD

**Issue by Cederman** [rangle/redux-beacon#138]
Hi!
I have implemented Redux Beacon with a React Native project that I'm working on using Google Tag Manager. I have created a middleware to dispatch events to GTM based my own action types but when I try to do the same for the dispatched actions that [React Navigation](https://reactnavigation.org/) uses, it doesn't trigger.

Have any of you got this working? The action types for React Navigation can be seen [here](https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js#L31).

The events map that I have set up looks like this:
`const eventsMap = {
  'Navigation/NAVIGATE': pageViewEvent,
};`

`Navigation/NAVIGATE` is the action dispatched when navigating using the React Navigation library.

Any help is greatly appreciated :)

**Comment by ttmarek** [comment]
Hey @Cederman, thanks for opening an issue.

It's odd that your custom actions are working but React Navigation's isn't. If possible, could you paste in your `pageViewEvent`. Also, can you see the `Navigation/NAVIGATE` action in redux-logger? Does Redux Beacon's [logger](https://rangle.github.io/redux-beacon/docs/extensions/logger.html) show anything?

**Comment by RobertSheaO** [comment]
@Cederman Here is how I did it. I logged out the entirety of the first and second params provided to the eventMap to build out what I needed. Your app navigation setup may vary, so my exact example may need to be modified for it to work for you.

```js
const eventsMap = {
  'Navigation/NAVIGATE': (action, prevState) => ({
    hitType: 'pageview',
    page: action.routeName,
    referrer: prevState.nav.routes[0].routes[prevState.nav.routes[0].index].routeName
  })
}
```

In order to get the `referrer` path, I just put `prevState.nav` as the referrer and looked at what was logged in the console using remote debugging.

I'll need to configure one for `Navigation/RESET`, which I use after login, and on logout; I suspect it will be highly customized for my use case.
