### ISSUE TITLE
Logger broken with IE 11

### ISSUE THREAD

**Issue by bobbysciacchitano** [rangle/redux-beacon#151]
I'm getting a error in IE 11 with the logger. Looking at the code, string.repeat isn't supported. Is there any way of replacing this with something else?

https://github.com/rangle/redux-beacon/blob/master/src/extensions/logger/logger.js#L26

**Comment by ttmarek** [comment]
@bobbysciacchitano Yes!

I'll be sure to replace `string.repeat` with something else in the next release. We added it in a rush to support console groups for React Native developers.

Until the next release, I recommend using v1.2.0 instead of v1.2.1 (there is no difference between these two releases for web developers):

```
npm install redux-beacon@1.2.0 --save
```

**Comment by ttmarek** [comment]
Should be fixed in the latest release: https://rangle.gitbook.io/redux-beacon/migration-guide-v1-to-v2
